adds editstaff form
Ameelio/connect-doc-client pull request #141
Opened 2021-11-03 12:33 UTC by lspdrz

Very rudimentary staff creation form. Does not allow support for editing current staff members yet but the scaffolding is there. Video example below

https://user-images.githubusercontent.com/9705113/140060578-23e28837-cdc0-4d25-a068-46d18cec6006.mov

2021-11-03 12:34 UTC, lspdrz commented on src/api/Common.ts
> +    throw new Error(`${responseJson.message}`);
@gabrielsaruhashi i'm being a little reckless here maybe? will this change affect anything else?

2021-11-04 02:03 UTC, gabrielsaruhashi commented on src/utils/constants/Common.ts
> +export enum StaffRoles {
nit: StaffRole

2021-11-04 02:03 UTC, gabrielsaruhashi commented on src/api/Common.ts
> +    throw new Error(`${responseJson.message}`);
do we really want to expose the error message to a DOC user?
I'd rather keep it opaque. Dev messages are often confusing

2021-11-04 02:04 UTC, gabrielsaruhashi commented on src/api/Common.ts
> +    throw new Error(`${responseJson.message}`);
Sentry is our best friend to capture the actual error

2021-11-04 02:04 UTC, gabrielsaruhashi commented on src/redux/modules/staff.ts
> +      showToast(
add sentry capture exception here

2021-11-04 02:05 UTC, gabrielsaruhashi commented on src/redux/modules/staff.ts
> +      showToast(CREATE_STAFF, "Staff member successfully created!", "success");
"${staff.firstName} ${staff.lastName} was added successfully as a staff member of the facility! "

2021-11-04 02:07 UTC, gabrielsaruhashi commented on src/redux/modules/staff.ts
> +    } catch (error) {
this catch is not needed. it seems like we're catching and re-throwing the same error message
builder.addcase error is already handling the rejection

2021-11-04 02:09 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +export type StaffData = {
hm I dont think this belongs to Common.ts

can't we just use the existing Staff type.
If not,  I'd just move it to the component itself. It's not being used anywhere else

2021-11-04 02:10 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +  const [createMode, setCreateMode] = useState(false);
nit could we prefix it with is to make it more clear that it's a boolean?

isCreating, setIsCreating

2021-11-04 02:10 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +          // onFinishFailed={onFinishFailed}
delete?

2021-11-04 02:12 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +  formItems: FormItem[];
![image](https://user-images.githubusercontent.com/12942772/140245863-c50d2642-3a48-4785-aa73-dbab59d9e805.png)
instead of recreating the type, I am pretty sure we could just use the actual FormItemProps from antd

2021-11-04 02:13 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +  enumValues?: string[];
having enumvalues in there feels a bit confusing
If we keep going with these types, I'd de-compose it into a union instead of keeping it nullable

2021-11-04 02:13 UTC, gabrielsaruhashi commented on src/components/Admin/EditStaff.tsx
> +  const saveStaff = (values: any) => {
what would it take for us to type this one?

2021-11-04 02:15 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +      <Button className="mb-5" onClick={() => setCreateMode(!createMode)}>
hmm I dont think this "createMode" is making the UI better
Let's just keep the form visible at all times?

2021-11-04 02:18 UTC, gabrielsaruhashi requested changes
it's cool that we're trying to abstract the form editing, but there are so many 'any's right now spread out. Im not sure if this abstraction is sustainable if we can't have some safeguards?
It's making it harder to read as well. I wonder if a simple form would have been more clear here

2021-11-04 02:19 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +    <>
Could we put this in a Card?
I'll follow the design we did for the Admin page
The floating fields look confusing

2021-11-04 11:13 UTC, lspdrz commented on src/api/Common.ts
> +    throw new Error(`${responseJson.message}`);
Well the inspiration was from testing. I spent 30 min to an hour trying to figure out why my form wasn't posting to the API correctly precisely because the error message so opaque. It ended up being a simple type error, I was inputting an invalid email, and this wasn't communicated. Not communicating these type errors will definitely be a pain point for the usage of this page

2021-11-04 11:16 UTC, lspdrz commented on src/redux/modules/staff.ts
> +      showToast(
I'm not sure this is desired behavior - do we really want to be logging sentry errors for every user mistake that will cause the validation to fall? E.g. mistakes on emails, phone numbers, urls....

Maybe we need to conditionallly send sentry errors? But then that opens the conversation/tasks of improving our validation error messages from the API

2021-11-04 11:21 UTC, lspdrz commented on src/redux/modules/staff.ts
> +    } catch (error) {
We need it to access the payload of the error message I believe, which I use in the showToast. If we remove that future and go for the opaque error message, I can remove this catch too.

```rejectWithValue(value, [meta]): rejectWithValue is a utility function that you can return (or throw) in your action creator to return a rejected response with a defined payload and meta. It will pass whatever value you give it and return it in the payload of the rejected action. If you also pass in a meta, it will be merged with the existing rejectedAction.meta.```

2021-11-04 11:23 UTC, lspdrz commented on src/typings/Common.ts
> +export type StaffData = {
We cannot, they're fundamentally different. And we're also using it in staff.ts in the redux files. I could move it and export it from the Staff.ts typing?

2021-11-04 11:34 UTC, lspdrz commented on src/components/Admin/Edit.tsx
> +  formItems: FormItem[];
These are different custom types for use with the admin pages

2021-11-04 11:35 UTC, lspdrz commented on src/typings/Common.ts
> +  enumValues?: string[];
Ok, let's talk about these types today

2021-11-04 11:36 UTC, lspdrz commented on src/components/Admin/EditStaff.tsx
> +  const saveStaff = (values: any) => {
I could create a type of accepted saveStaff values

StaffValue = string | boolean | StaffRole.

I think this would sort out the anys everywhere

2021-11-04 11:37 UTC, lspdrz commented on src/components/Admin/Edit.tsx
> +      <Button className="mb-5" onClick={() => setCreateMode(!createMode)}>
Let's talk. This is done to provide scaffolding for a view where we'll have a table to edit existing rows of data. All of this is design is in line with typical admin UIs

2021-11-04 11:42 UTC, lspdrz commented
@gabrielsaruhashi let's talk about the abstraction today. The whole point of the abstraction was to have the Edit Page be a reusable component across all admin pages, to introduce a standardized way of adding data to the backend in line with other admin sites I've used, particularly Django Admin. As you can see on the create facility PR, it's already being used a second time. So the reasoning was DRY and simple and standard input across all data entry

2021-11-04 18:13 UTC, gabrielsaruhashi commented on src/redux/modules/staff.ts
> +    } catch (error) {
Let's go with opaque messages
we're not reviewing copy for the error messages to make sure they're user friendly.
I'd rather just throw on sentry

2021-11-04 18:13 UTC, gabrielsaruhashi commented on src/redux/modules/staff.ts
> +      showToast(
I see now disregard the sentry comment

2021-11-04 18:13 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +  enumValues?: string[];
It's the same technique we talked about for ModalData

2021-11-04 18:16 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +export type StaffData = {
Staff.ts would make more sense
Can we call it TCreateStaff ? Or anything to make it clear what's the use case

2021-11-04 18:17 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +  enumValues?: string[];
https://github.com/Ameelio/connect-doc-client/blob/573e13d1ce8871e382e476727d6b330645202a7b/src/typings/Modal.ts

2021-11-04 18:18 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +  const [isCreating, setIsCreating] = useState(false);
is this being used?

2021-11-04 18:33 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +        <Form form={createForm} onFinish={saveEntity}>
I'd just expose the Form directy. 
This "add new" button is not really improving the UI imo

2021-11-04 18:35 UTC, gabrielsaruhashi commented on src/components/Admin/EditStaff.tsx
> +  const saveStaff = (values: any) => {
we should just have values: CreateStaffDto imo
and do the cleaning up on the child component

2021-11-04 18:40 UTC, gabrielsaruhashi commented on src/api/Common.ts
> +    throw new Error(`${responseJson.message}`);
This is gonna impact every single API call the DOC makes.
We don't want to scare the DOC staff with error messages thrown on the API whose copy we're not reviewing. ('Entity not found', etc.)
Debugging as a developer should be possible using "Network" and "Redux Toolkit".
If what we're solving for is giving feedback to andrew, i'd unwrap the thunks

2021-11-04 18:41 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +  formItems: FormItem[];
what will it take to type it? This is what I am trying to solve for.
'Any' shouldn't be the typing here
I'd make it a generic type 
onCreate<T>: (values: T) => void;

2021-11-04 18:43 UTC, gabrielsaruhashi commented on src/utils/constants/Common.ts
> +export enum StaffRole {
this value already exists in User.d.ts - I'd just make sure we delete that one over there
User.d.ts is legacy --- it shouldn't be tehre
but I'd create 
a new User.ts and have StaffRole export from there (and delete teh one on User.d.ts)

2021-11-05 10:51 UTC, gabrielsaruhashi commented on src/api/Common.ts
> +    throw new Error(`${responseJson.message}`);
Could we just pass an optional parameter for now? 
surfaceErrorMessage?: boolean

We should only turn it on for form creation right now as the feedback is actually actionable.

For GET requests / etc, I am not confident yet that our error messages are good.

2021-11-05 11:12 UTC, lspdrz commented on src/components/Admin/EditStaff.tsx
> +  const saveStaff = (values: any) => {
We can't do that and maintain the abstraction of the child component to be used with different parent components and different form structures

2021-11-05 13:50 UTC, lspdrz commented on src/utils/constants/Common.ts
> +export enum StaffRole {
When I create a new User.ts file, it's really messing up the imports with User.d.ts. I'm correcting the StaffRole string in User.d.ts for now and we can continue using that one.

I also can't remove it from that file because it's being used in the Staff type in the same file

2021-11-05 14:01 UTC, lspdrz commented on src/components/Admin/Edit.tsx
> +  formItems: FormItem[];
What exactly is the use of that? I can't pass that type up to the parent component. I think this is an ok case for any, because we do want to receive any type of values. The type constraints occur in the createStaff function in the parent component, EditStaff.

Also noting that antd uses any for these values in the above image

2021-11-05 21:27 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +      <Button className="mb-5" onClick={() => setCreateMode(!createMode)}>
I see what you're striving to acheive. In this case, the Edit staff page already exists. This is a placeholder solution for create staff
I think we're perceiving the scope of the task differently. These two pages are makeshift solutions, but they will eventually merge into our existing UI/UX that uses drawers as a way to create new entities.

2021-11-05 21:28 UTC, gabrielsaruhashi commented on src/components/Admin/EditStaff.tsx
> +  const saveStaff = (values: any) => {
I believe we can if we type onSave using the generic <T> type that I proposed. That's the main use case for generic types

2021-11-05 21:29 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +  formItems: FormItem[];
antd's typing is not great
check comment below to understand the use case of generic types
Here's documentation that will help: https://www.typescriptlang.org/docs/handbook/2/generics.html

2021-11-08 21:35 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +  placeholder: any;
should this be any?

2021-11-08 21:36 UTC, lspdrz commented on src/typings/Common.ts
> +  placeholder: any;
yes, it can be any type. String, boolean, array...

2021-11-08 21:57 UTC, gabrielsaruhashi requested changes
I'm still wondering what we're gaining with this abstraction. I'd have rather started with a simple solution, and shipped that fast like we outlined on the ticket, instead of trying to abstract it right away and spending a week on it. 
These were supposed to be two temporary admin features. This Edit component won't be able to be reused for MeetingSlots, Kiosk creation etc.

2021-11-08 21:57 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +  required: boolean;
might be convenient to make it optional
required?: boolean

2021-11-08 21:57 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +      case "boolean":
why not create a separate type field like the one we discussed? wouldn't it be more explicit to have a typeof and assigning a dummy placeholder name to identify a boolean?
This feels a bit hacky.

2021-11-08 21:57 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +    if (formItem.selectOptions) {
Same here:
Why not have a "type" in the FormItem for "select" like we discussed?
That'd be more clear typing + reading

2021-11-08 21:57 UTC, gabrielsaruhashi commented on src/redux/modules/staff.ts
> +    } catch (error) {
Im pretty positive u don't need this.
I grab error messages from payload.error.message

2021-11-08 21:57 UTC, gabrielsaruhashi commented on src/redux/modules/staff.ts
> +        `Failed to create staff member: ${action.payload}`,
have u tried action.error.message?

2021-11-08 21:57 UTC, gabrielsaruhashi commented on src/redux/modules/staff.ts
> +        `Failed to create staff member: ${action.payload}`,
when it throws u shouldn't use a payload

2021-11-08 21:57 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +  const setValue = (value: any, name: string) =>
couldn't we type name to be 
`keyof FormItem`

2021-11-08 21:57 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +  selectOptions?: StaffRole[];
We discussed this briefly on the previous PR, but I'd do something like

item: SelectFormItem | CheckboxFormItem | TextFieldFormItem

each of them can have a type and their specifc metadata e.g

SelectFormItem {
  type: 'select',
  options: string[]
} 

and have all the particular implementations in there instead of having multiple null fields / secret keywords

2021-11-08 22:11 UTC, lspdrz commented on src/components/Admin/Edit.tsx
> +      case "boolean":
This is really an implementation detail that would require a lot of changes and re-testing on my part. Worth doing instead of getting it into main for Andrew?

2021-11-08 22:15 UTC, lspdrz commented
> I'm still wondering what we're gaining with this abstraction. I'd have rather started with a simple solution, and shipped that fast like we outlined on the ticket, instead of trying to abstract it right away and spending a week on it. These were supposed to be two temporary admin features. This Edit component won't be able to be reused for MeetingSlots, Kiosk creation etc.

I went with the abstraction because I always abstract a component in React when I see/foresee it being reused, and it was supposed to be a simple abstraction. Was not supposed to take a week. But I agree this is not a productive workflow. It's going to take another hour at least to implement the next iteration of review comments and test them, which I will do tomorrow morning my time. I'm also going to try to write up a timeline of the work on this ticket so we can improve the workflow as this is not sustainable

2021-11-09 08:51 UTC, lspdrz commented on src/components/Admin/Edit.tsx
> +  const setValue = (value: any, name: string) =>
Throwing type errors

2021-11-09 09:28 UTC, lspdrz commented on src/components/Admin/Edit.tsx
> +  const setValue = (value: any, name: string) =>
![image](https://user-images.githubusercontent.com/9705113/140898194-a5e020f1-4908-4158-877c-f0a95735a059.png)

2021-11-09 13:07 UTC, gabrielsaruhashi commented on src/typings/Common.ts
> +  placeholder: boolean;
what does placeholder mean for a boolean field?

2021-11-09 13:12 UTC, gabrielsaruhashi approved these changes

2021-11-09 13:12 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +          <Checkbox
nit: 
<Checkbox  ... />

2021-11-09 13:12 UTC, gabrielsaruhashi commented on src/components/Admin/Edit.tsx
> +      case "boolean":
I think that it would add too much debt.
The better approach imo would have been to go for a simple for for the two pages and then worked on a proper abstraction as fast-follows if/when we saw the need

2021-11-09 13:12 UTC, gabrielsaruhashi commented on src/components/Admin/EditStaff.tsx
> +        placeholder: false,
I think initialValue is a better name here

2021-11-09 13:12 UTC, gabrielsaruhashi commented on src/typings/Staff.ts
>    facilityId: string;
note that we need to update this type since the staff changes

2021-11-09 13:20 UTC, lspdrz commented on src/typings/Common.ts
> +  placeholder: boolean;
it's not being used right now but it would allow us to set the default on the Checkbox

2021-11-09 13:22 UTC, lspdrz commented on src/typings/Staff.ts
>    facilityId: string;
I don't understand what you mean here

2021-11-09 21:33 UTC, merged