pending messages review page: loading connections & fetching messages
Ameelio/connect-doc-client pull request #152
Opened 2021-11-09 21:20 UTC by gabrielsaruhashi

## Proposed changes
Foundational work for the pending messages review page.
![image](https://user-images.githubusercontent.com/12942772/141006494-0c082fd5-ace9-47fa-a5b9-741267de5041.png)

2021-11-09 21:49 UTC, cainlevy requested changes

2021-11-09 21:49 UTC, cainlevy commented on src/graphql/GetConnection.graphql
> +query GetConnection($id: ID!) {
GetConnectionMessages? GetConnectionTimeline?

2021-11-09 21:49 UTC, cainlevy commented on src/pages/MessageReviewPage.tsx
> +      variables: { id: facilityId || "" },
we should eliminate the null case of `facilityId` some other way. maybe throw an error? this would cause an error anyway, but a less helpful one.

2021-11-09 21:49 UTC, cainlevy commented on src/graphql/GetConnection.graphql
> +          ...MessageFragment
i have a feeling that we could get into trouble with fragments that load nested relations. it makes them less reusable and we'll have to watch out for circular loading.

if we use small fragments we can always compose them:

```suggestion
          ...MessageFragment
          connection {
            ...ConnectionFragment
            inmate {
              ...InmateFragment
            }
            visitor {
              ...VisitorFragment
            }
          }
```

2021-11-09 21:49 UTC, cainlevy commented on src/pages/MessageReviewPage.tsx
> +    setConnections(connections);
i realize this is just a way of getting started but we should build this timeline in the backend, even if it's composited together from multiple database queries for now. our goal should be a timeline that can paginate.

2021-11-10 19:20 UTC, gabrielsaruhashi commented on src/pages/MessageReviewPage.tsx
> +    setConnections(connections);
i see makes sense! 
Do you agree with the typing strategy? @cainlevy 
I'll just move the types the backend and do the conversions backend side
I am unfortunately tied up all day today, but I will have time tmr.

2021-11-10 19:34 UTC, cainlevy commented on src/pages/MessageReviewPage.tsx
> +    setConnections(connections);
yeah the union type makes sense to me! we'll end up publishing it over graphql and then referencing `__typename` to narrow the types during render.

2021-11-10 19:34 UTC, cainlevy commented on src/pages/MessageReviewPage.tsx
> +    setConnections(connections);
https://www.apollographql.com/docs/apollo-server/schema/unions-interfaces/

2021-11-16 14:28 UTC, gabrielsaruhashi commented on src/pages/MessageReviewPage.tsx
> +    setConnections(connections);
awesome. on it

2021-11-17 01:45 UTC, cainlevy approved these changes

2021-11-17 01:45 UTC, cainlevy commented on src/components/MessageReviewPanel/ConnectionListSidebar/ConnectionListSidebar.tsx
> +export type TConnectionListItem = {
Why "T"? Is that a local convention?

2021-11-17 01:45 UTC, cainlevy commented on src/graphql/fragments/MessageFragment.graphql
> +  senderId
What value is this? Is it a malan ID? Are we exposing those to the API?

The answer may be in the backend but ... phone.

2021-11-17 01:45 UTC, cainlevy commented on src/graphql/fragments/VisitorFragment.graphql
> +  malanId
What's the use case for malanId in the frontend? I'm hopeful we can hide it behind our GraphQL API. Maybe trying to put the cat back in the bag here.

2021-11-17 01:45 UTC, cainlevy commented on src/pages/MessageReviewPage.tsx
> +  useEffect(() => {
This looks like a useMemo.

But really it's going to save very little. This component should re render very rarely as staff select new connections.

2021-11-17 01:45 UTC, cainlevy commented on src/pages/MessageReviewPage.tsx
> +  useEffect(() => {
Looks like a useMemo (or just bare JS, really)

2021-11-17 01:45 UTC, cainlevy commented on src/pages/MessageReviewPage.tsx
> +    queryConnection({ variables: { id: connection.id } });
I suspect you could also have a standard useQuery and let Apollo notice when the argument changes. There's even a "skip" option for when the current value is null.

I don't know if one implementation is better. We have options!

2021-11-18 13:37 UTC, gabrielsaruhashi commented on src/components/MessageReviewPanel/ConnectionListSidebar/ConnectionListSidebar.tsx
> +export type TConnectionListItem = {
I personally like doing this when I have a component-level props that is exportable / reusable elsewhere
It make more clear the relationship between the two

2021-11-18 13:37 UTC, gabrielsaruhashi commented on src/graphql/fragments/MessageFragment.graphql
> +  senderId
Yep! Malan ID
The service function for createMessage that I created ensures we use malan

2021-11-18 13:38 UTC, gabrielsaruhashi commented on src/graphql/fragments/VisitorFragment.graphql
> +  malanId
We'd use to detect whether the sender is a user or an inmate
We can do that conversion at the resolver level, though

2021-11-18 13:39 UTC, gabrielsaruhashi commented on src/pages/MessageReviewPage.tsx
> +    queryConnection({ variables: { id: connection.id } });
oh interesting! 
I liked this one because it makes it pretty clear that the query is reactive to a UI interaction
happy to explore more on fast-follow PRs

2021-11-18 13:42 UTC, gabrielsaruhashi commented on src/pages/MessageReviewPage.tsx
> +  useEffect(() => {
idk im always so wary of memoization for inexpensive computations lol, but I agree it's more clear. Cool with just doing that for useStart / useEffect combos

2021-11-18 13:50 UTC, merged