Revert "Revert "Connection Drawer""
Ameelio/connect-doc-client pull request #166
Opened 2021-11-18 17:23 UTC by lspdrz

Reverts Ameelio/connect-doc-client#162

2021-11-18 18:31 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +    <Descriptions.Item label='Disabled by' labelStyle={{
i believe react will complain about a missing key

2021-11-18 18:32 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +  const contents = [
Why not just treat it as a single React.ReactNode instead of an array of React.ReactNode with a single item -- i.e I think u can just move this inside the description.item

2021-11-18 18:33 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +              TODO: Re-introduce when we have an emessaging meetingtype
link to shortcut story?

2021-11-18 18:34 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +            <Descriptions.Item label="Incarcerated Person" labelStyle={labelStyle}>
ideally we would override the antd theme, but this works for now

2021-11-18 18:35 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +              {`${connection.contact.email}`}
instead of applying label style N times for each of the n rows, I think we should move this to a wrapper <DescriptionItem  /> that does this for us

2021-11-18 18:36 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +            <Row className=''>
why wrap the buttons with Rows? You can probably just have the buttons here

2021-11-18 18:36 UTC, gabrielsaruhashi commented on src/components/Requests/StaffCell.tsx
> +        {`${staff.firstName} ${staff.lastName}`}
genFullName(staff)

2021-11-18 18:37 UTC, gabrielsaruhashi requested changes
left a couple of comments as i reviewed

2021-11-18 21:37 UTC, lspdrz commented on src/components/Profile/Connections/ConnectionItem.tsx
> +  const contents = [
Do you mean create four description.items and return them? that's what I had before and Jordan rightfully pointed out it wasn't very DRY, so now we're mapping the array

2021-11-18 21:37 UTC, lspdrz commented on src/components/Profile/Connections/ConnectionItem.tsx
> +    <Descriptions.Item label='Disabled by' labelStyle={{
Will sort out when we solve above

2021-11-22 21:30 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +  const contents = [
I see I think this array with a JSX.element and two strings is what's confusing. Could you just move them inside the return JSX?

2021-11-22 21:31 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +const getRestrictionDetails = (restriction: ConnectionRestriction) => {
this is returning JSX so I'd just follow standard component naming
<RestrictionDetails />

2021-11-22 21:32 UTC, gabrielsaruhashi commented on src/components/Profile/Connections/ConnectionItem.tsx
> +              {callRestriction && getRestrictionDetails(callRestriction)}
then here you do <RestrictionDetails/> instead of doing this function notation

2021-11-24 15:56 UTC, lspdrz commented on src/components/Profile/Connections/ConnectionItem.tsx
> +              {`${connection.contact.email}`}
CAn't do this because wrapper components don't work for Description.Item: https://github.com/ant-design/ant-design/issues/27411

2021-11-24 16:09 UTC, lspdrz commented on src/components/Profile/Connections/ConnectionItem.tsx
> +  const contents = [
CAn't do this because wrapper components don't work for Description.Item: ant-design/ant-design#27411

2021-11-24 16:09 UTC, lspdrz commented on src/components/Profile/Connections/ConnectionItem.tsx
> +const getRestrictionDetails = (restriction: ConnectionRestriction) => {
CAn't do this because wrapper components don't work for Description.Item: ant-design/ant-design#27411

2021-11-24 16:09 UTC, lspdrz commented on src/components/Profile/Connections/ConnectionItem.tsx
> +              {callRestriction && getRestrictionDetails(callRestriction)}
CAn't do this because wrapper components don't work for Description.Item: ant-design/ant-design#27411

2021-11-24 19:37 UTC, gabrielsaruhashi approved these changes

2021-11-25 15:17 UTC, merged