meeting slots simplfied
Ameelio/connect-doc-client pull request #172
Opened 2021-11-23 14:35 UTC by gabrielsaruhashi

## Proposed changes
[sc-967]

2021-11-23 20:02 UTC, gabrielsaruhashi commented on src/components/Settings/MeetingSlotSettings.tsx
> +function nextMeetingSlotStart(slot: TentativeCallSlot) {
this is needed because antd's time picker returns a date object w/ the current second/milliseconds

2021-11-23 20:02 UTC, gabrielsaruhashi commented on src/components/Settings/MeetingSlotSettings.tsx
> +function resetDate(date: Date) {
this is needed because antd's time picker returns a date object w/ the current second/milliseconds

2021-11-23 20:03 UTC, gabrielsaruhashi commented on src/components/Settings/MeetingSlotSettings.tsx
> +type WeeklyMeetingSlotSchedule = {
because of the way deleting a call slot works, I chose to go with a dictionary indexing so we know exactly which meeting slot to delete

2021-11-23 21:11 UTC, cainlevy requested changes

2021-11-23 21:11 UTC, cainlevy commented on src/components/Settings/MeetingSlotSettings.tsx
> +type WeeklyMeetingSlotSchedule = {
there's a lot of complexity in this pull request dedicated to maintaining and mutating the dictionary. i understand dictionaries are good for constant-time lookups, but i don't see how it helps deletion and i haven't found any spots where the complexity seems motivated given the range of expected feature usage.

2021-11-23 21:11 UTC, cainlevy commented on src/components/Settings/MeetingSlotSettings.tsx
> +// Indexing by start time ensures no duplicate call slots for the same range
does the overlap validation logic already cover this?

2021-11-23 21:11 UTC, cainlevy commented on src/components/Settings/MeetingSlotSettings.tsx
> +              start.setMinutes(slot.minute);
nextMeetingSlotStart?

2021-11-23 21:11 UTC, cainlevy commented on src/components/Settings/MeetingSlotSettings.tsx
> +                    moment(formatDate(end, "time"), dateFormat),
waaaait we're converting `{hour, minute}` into `Date` just so we can stringify into `HH:mm`? 👀

2021-11-26 22:09 UTC, gabrielsaruhashi commented on src/components/Settings/MeetingSlotSettings.tsx
> +    const r = { ...weeklySchedule };
ooh yes. 
I had a util for this cloning
I had a hunch that this was not enough

2021-11-26 22:09 UTC, gabrielsaruhashi commented on src/components/Settings/MeetingSlotSettings.tsx
> +// Indexing by start time ensures no duplicate call slots for the same range
You're right!
The overlapping logic happened after this naive initial version . Will clean up now

2021-11-26 22:14 UTC, gabrielsaruhashi commented on src/components/Settings/MeetingSlotSettings.tsx
> +                    moment(formatDate(end, "time"), dateFormat),
I think it's easier to use Date operations. The alternative is to manually compute the end hour minute based on the slot start time and a duration in milliseconds

2021-11-26 22:16 UTC, gabrielsaruhashi commented on src/components/Settings/MeetingSlotSettings.tsx
> +    );
i considered! but we're actually removing the lodash dependency asap as that seems 
The refactor makes this more legible :)

2021-11-26 22:35 UTC, gabrielsaruhashi commented on src/utils/Common.ts
> +}
it does!  I see it's in draft morde, this is new right? 
I remember looking it up a while back, and Im pretty sure i did not see any es6+ equivalent

2021-11-29 16:32 UTC, cainlevy commented on src/utils/Common.ts
> +}
🤔 if typescript allows it, i think you're good. it'll take care of transpiling into es5 (our current tsconfig target).

2021-11-29 16:41 UTC, cainlevy approved these changes

2021-11-29 16:41 UTC, cainlevy commented on src/components/Settings/MeetingSlotSettings.tsx
> +// Indexing by start time ensures no duplicate call slots for the same range
comment is out of date?

2021-11-29 16:48 UTC, merged