Disable submit/confirm buttons on click
Ameelio/connect-doc-client pull request #173
Opened 2021-11-23 17:49 UTC by wittejm

To prevent double-click errors.

2021-11-23 20:05 UTC, gabrielsaruhashi commented on src/components/Settings/AddEditKeywordModal.tsx
> +  const [saveButtonDisabled, setSaveButtonDisabled] = useState(false);
im pretty sure useMutation returns this information.
Have you checked the documentation?

2021-11-23 20:08 UTC, gabrielsaruhashi requested changes

2021-11-23 20:08 UTC, gabrielsaruhashi commented on src/components/Settings/AddEditKeywordModal.tsx
> +  const [saveButtonDisabled, setSaveButtonDisabled] = useState(false);
https://www.apollographql.com/docs/react/data/mutations/#executing-a-mutation

2021-11-23 20:08 UTC, gabrielsaruhashi commented on src/components/Settings/AddEditKeywordModal.tsx
> +  const [saveButtonDisabled, setSaveButtonDisabled] = useState(false);
You don't need to track this independently

2021-11-23 20:08 UTC, gabrielsaruhashi commented on src/components/Settings/ConfirmOverride.tsx
> +          <Button style={{ "marginLeft": "auto" }} onClick={onClickNo}>No</Button>
We prefer using tailwind whenever possible. 
className="ml-auto"

2021-11-23 20:08 UTC, gabrielsaruhashi commented on src/components/Settings/ConfirmOverride.tsx
> +      <InfoCircleFilled className="pt-3 pr-3" style={{ color: "#FAAD14", verticalAlign: 'middle' }} />
tailwind? 
Tailwind has a 100-900 color system as well

2021-11-23 20:31 UTC, cainlevy commented
Some day I hope we invest in components that make it easier to remember things like this. For example, we could create some Button wrapper that requires us to pass a `loading: boolean` prop.

2021-11-23 21:15 UTC, wittejm commented on src/components/Settings/ConfirmOverride.tsx
> +      <InfoCircleFilled className="pt-3 pr-3" style={{ color: "#FAAD14", verticalAlign: 'middle' }} />
The color here "Calendula Gold / 6" doesn't have a match in Tailwind. Approximate with ~Amber 600  or stick with the design?

2021-11-23 21:44 UTC, wittejm commented on src/components/Settings/ConfirmOverride.tsx
> +    <div className="flex" style={{ maxWidth }}>
I think I want to stick with `style={{}}` here because the tailwind smallest maxWidth is too big.

2021-11-24 22:04 UTC, gabrielsaruhashi commented on src/components/Settings/ConfirmOverride.tsx
> +    <div className="flex" style={{ maxWidth }}>
makes sense -

2021-11-24 22:05 UTC, gabrielsaruhashi commented on src/components/Settings/ConfirmOverride.tsx
> +    <div className="flex" style={{ maxWidth }}>
curious about why we need the max width - is that to make sure we wrap the text in case the previousEditorFullName is long?

2021-11-24 22:05 UTC, gabrielsaruhashi commented on src/components/Settings/ConfirmOverride.tsx
> +    <div className="flex" style={{ maxWidth }}>
If ye it might make sense to just pick a fixed size in rem?
e.g "w-48"

2021-11-24 22:05 UTC, gabrielsaruhashi approved these changes

2021-11-24 23:08 UTC, wittejm commented on src/components/Settings/ConfirmOverride.tsx
> +    <div className="flex" style={{ maxWidth }}>
It's just really small as a popover to confirm an edit and larger as a modal to confirm a delete. There's actually no reason to use maxWidth over width, and that's cool, I didn't realize width rem could be anything using tailwind.

2021-11-24 23:20 UTC, merged