adds active restriction lisit to visitor dashboard
Ameelio/connect-doc-client pull request #182
Opened 2021-11-30 17:21 UTC by lspdrz

DO NOT MERGE UNTIL https://github.com/Ameelio/connect-api-nest/pull/526 is merged and deployed

[sc-1491]

![image](https://user-images.githubusercontent.com/9705113/144096331-a1ec707f-e0af-47e9-b007-afa0114e4ea2.png)

2021-11-30 20:20 UTC, gabrielsaruhashi commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +  console.log('hi data')
✂️

2021-11-30 22:06 UTC, lspdrz commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +  console.log('hi data')
Done!!

2021-12-01 02:19 UTC, gabrielsaruhashi commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +  const { loading, error, data } = useQuery(GetVisitorWithRestrictionsDocument, {
we should keep components from src dummy. 
Let's pass it down as props and do this query at the top-level ContactPage.
It's probably an opportunity to start using the Visitor graphql type here instead of the old Contact (can be a fast-follow PR)
The Visitor graphql type has all the info Contact has

2021-12-01 02:20 UTC, gabrielsaruhashi requested changes
some comments!

2021-12-01 14:47 UTC, lspdrz commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +  const { loading, error, data } = useQuery(GetVisitorWithRestrictionsDocument, {
Done with the above. The Visitor graphql type doesn't have all the info Contact has, such as dateOfBirth. Down to take care in another story

2021-12-02 13:50 UTC, gabrielsaruhashi commented on src/graphql/GetVisitorWithRestrictions.graphql
> +        id
RestrictionFragment?

2021-12-02 13:51 UTC, gabrielsaruhashi commented on src/pages/ContactPage.tsx
> +        <ContactProfileHeader contact={contact} connections={data?.visitor.connections} facilityName={facilityName} />
data?.visitor.connections || []

no need to pass down an undefined

2021-12-02 13:51 UTC, gabrielsaruhashi commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +  connections: Connection[] | undefined;
connections: Connection[]

you should have a fallback to prevent undefined from being passed

2021-12-02 13:51 UTC, gabrielsaruhashi commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +            connections && connections.map(
this wont be needed once you have the fallback

2021-12-02 13:52 UTC, gabrielsaruhashi commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +                <div>
you're missing a key

2021-12-02 13:52 UTC, gabrielsaruhashi commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +                restriction =>
is prettier not being run upon committing?
this doesn't look formatted

2021-12-02 13:53 UTC, gabrielsaruhashi commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +      case (MeetingType.InPersonNoContact):
so currently we cannot create a connection restriction for e-messaging?

2021-12-02 13:54 UTC, gabrielsaruhashi commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +      case (MeetingType.InPersonNoContact):
it'd be an important use case.
that's the one that's driven us to create this in the first place

2021-12-02 13:54 UTC, gabrielsaruhashi commented on src/graphql/GetVisitorWithRestrictions.graphql
> +    firstName
you can use VisitorFragment here

2021-12-02 13:55 UTC, gabrielsaruhashi approved these changes
could you please address the comments? and or make sure we address them on the next PR

2021-12-02 14:04 UTC, lspdrz commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +                restriction =>
should be? I wrapped in parentheses hopefully it'll help it

2021-12-02 14:04 UTC, lspdrz commented on src/components/Profile/ProfileHeader/ContactProfileHeader.tsx
> +      case (MeetingType.InPersonNoContact):
We don't have the Meeting Type for emessaging in the backend yet

2021-12-02 14:05 UTC, lspdrz commented on src/graphql/GetVisitorWithRestrictions.graphql
> +    firstName
Can we? I want to include the restrictions and inmate foreign keys here but they're not on the fragment. We probably don't want to load those objects all the time either so I don't want to move to the fragment

2021-12-02 14:12 UTC, lspdrz commented
> could you please address the comments? and or make sure we address them on the next PR

Implemented requested changes and addressed a couple of comments. Will merge when tests pass.

Regarding the emessaging type: I'm going to add the meeting type to backend and uncomment the frontend features in one story. We need to think about the repercussions of adding another meeting type enum value will have to other features on the project

2021-12-02 14:12 UTC, merged