Update `Settings` page to edit `Schedules` instead of meeting slots
Ameelio/connect-doc-client pull request #326
Opened 2022-07-05 22:00 UTC by dabbler0

WIP

2022-07-08 05:58 UTC, crcommons commented on src/components/Settings/AddScheduleDrawer.tsx
> +                MeetingType.InPersonNoContact,
Is there a reason you manually constructed this array? If not, let's go with `Object.values(MeetingType)` to get the array, which will future proof this

2022-07-08 05:59 UTC, crcommons commented on src/components/Settings/AddScheduleDrawer.tsx
> +                    key={meetingType}
In case there were every two values in meetingType that were the same, consider using the index as the key instead

2022-07-08 06:02 UTC, crcommons commented on src/components/Settings/AddScheduleDrawer.tsx
> +              <Select.Option value={group.id}>{group.name}</Select.Option>
missing `key` which is probably throwing a warning in the console

2022-07-08 06:03 UTC, crcommons commented on src/components/Settings/AddScheduleDrawer.tsx
> +              <Select.Option value={kiosk.id}>{kiosk.name}</Select.Option>
same here, missing `key`

2022-07-08 06:05 UTC, crcommons commented on src/components/Settings/EditKioskDrawer.tsx
> +              <Select.Option value={group.id}>{group.name}</Select.Option>
`key` missing here as well

2022-07-08 06:09 UTC, crcommons commented on src/components/Settings/EditScheduleDrawer.tsx
> +              <Select.Option value={kiosk.id}>{kiosk.name}</Select.Option>
`key`

2022-07-08 06:10 UTC, crcommons commented on src/components/Settings/EditScheduleDrawer.tsx
> +            <Select.Option value={group.id}>{group.name}</Select.Option>
`key`

2022-07-08 06:16 UTC, crcommons commented on src/components/Settings/KioskSettings.tsx
> +    columns.push({
Just for consideration.... for visual clarity and code readability, you can completely construct the array without the `groups` object and then after it is defined use `column.splice(index, 0, item);` swapping out index and item for the values you want. This way you won't need to break up the array definition.

2022-07-08 06:28 UTC, crcommons commented on src/components/Settings/MeetingSlotDrawer.tsx
> +      <ScheduleMeetingSlotSettings onClose={onClose} schedule={schedule} />
Given the length of this file, it would be nice to move ScheduleMeetingSlotSettings to another file.

2022-07-08 06:42 UTC, crcommons requested changes
Woah, this is a lot of code!! nice job! 

I did my best to review in depth, but not positive I caught everything. If there are any areas where you have concerns, let me know and I will give an extra thorough review. Otherwise, a few small issues, but nothing major. 

My only question is, if all of the changes have been implemented and deployed in the API, do we need the feature flag?

2022-07-08 15:30 UTC, dabbler0 commented
A couple outstanding PRs in `connect-api-nest` should be merged before we enable the feature flag -- #1004, #1005 (necessary, fixes some parts of the new api that these doc changes depend on), and #1006 (not necessary, but good for quality of life because without it sometimes there is an overflow of new schedules).

2022-07-08 16:04 UTC, crcommons commented
> A couple outstanding PRs in `connect-api-nest` should be merged before we enable the feature flag -- #1004, #1005 (necessary, fixes some parts of the new api that these doc changes depend on), and #1006 (not necessary, but good for quality of life because without it sometimes there is an overflow of new schedules).

ok sounds good. just wanted to check since that original PR was merged

2022-07-08 18:57 UTC, dabbler0 commented on src/components/Settings/AddScheduleDrawer.tsx
> +                MeetingType.InPersonNoContact,
This was just copied from `AddKioskDrawer`, but I think it is because we need to exclude voice calls.

2022-07-08 19:28 UTC, dabbler0 commented on src/components/Settings/AddScheduleDrawer.tsx
> +              <Select.Option value={group.id}>{group.name}</Select.Option>
Fixed this in all the `Selects`, but am still getting a "needs unique key" warning in the console. The warning seems to be coming from the `<Table>` in `KioskSettings` and `ScheduleSettings` (if I remove that table but keep the drawers then the error goes away), but I can't figure out what I'm doing wrong.

2022-07-08 19:37 UTC, dabbler0 commented on src/components/Settings/AddScheduleDrawer.tsx
> +              <Select.Option value={group.id}>{group.name}</Select.Option>
Ah, what was needed was `rowKey` on the antd `Table`. Should be all resolved now.

2022-07-20 20:30 UTC, cainlevy approved these changes
as far as i can tell this is all properly gated by a feature flag which makes reduces the risk of merging it out.

next time, i would encourage taking advantage of the feature flag to merge more smaller branches. large, long-lived branches are harder to maintain (merge) and can sometimes limit access to useful bits of the partial solution.

as it is, though, everything looks good (my comments are mostly administrative) and ready to go from my perspective.

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/AddScheduleDrawer.tsx
> +                      }
this kind of logic is sometimes handled with a `useEffect`, e.g.

```
// clear kiosks when the meeting type changes
useEffect(() => {
  setSelectedKiosks([]);
}, [selectedMeetingType]);
```

i don't think this is worth changing now but i wanted to share so you have options next time.

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/CreateSchedule.graphql
> +      meetingType
could move to `ScheduleFragment`

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/CreateSchedule.graphql
> +      visitorTypes
could move to `ScheduleFragment`

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/EditScheduleDrawer.tsx
> +}
given how much is going on in this file, it may be worth extracting `DetailsProps` and `ScheduleDetailsTable` into a separate file

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/EditScheduleDrawer.tsx
> +}
i would also encourage extracting `FormProps` and `EditScheduleForm` into a separate file

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/ScheduleSettings.tsx
> +};
this looks like it could be extracted and shared with `EditScheduleDrawer`.

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/ScheduleSettings.tsx
> +};
this seems like a nice generic utility component. we don't have a specific location for utility components in the DOC client so i started adding them to `src/components` but i think `src/utils` may be better.

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/GetFacilitySchedules.graphql
> +      meetingType
could move to `ScheduleFragment`

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/GetFacilitySchedules.graphql
> +      visitorTypes
could move to `ScheduleFragment`

2022-07-20 20:30 UTC, cainlevy commented on src/components/Settings/ScheduleMeetingSlotSettings.tsx
> +}
i think i saw this earlier. is it implemented multiple times in the final solution? might be worth finding a way to keep a single copy of the function. one option might be in its own co-located file (e.g. `./nextMeetingSlot.ts`) or with some of its siblings in a local collection of functions (e.g. `./scheduleUtils.ts`).

2022-07-20 20:30 UTC, cainlevy commented on src/graphql/GetSchedulesForFacility.graphql
> +}
is this still used? it fetches a surprisingly small amount of data.

2022-07-20 20:30 UTC, cainlevy commented on src/redux/modules/schedule.ts
> +export const schedulesSlice = createSlice({
in the end i'm still unsure if we need this redux module. i don't recall seeing any selectors that read from it.

if it's currently essential to the functionality of the pull request, let's keep it and revisit in a follow up. if it's not essential, maybe it's cheap to remove?

2022-07-20 20:31 UTC, dabbler0 commented on src/redux/modules/schedule.ts
> +export const schedulesSlice = createSlice({
Not essential; I made this to mimic the way we treat kiosks in case it is something we like to use. I'll remove it.

2022-07-20 20:37 UTC, dabbler0 commented on src/graphql/GetSchedulesForFacility.graphql
> +}
Seems not, removing.

2022-07-20 21:04 UTC, merged